[package]
name = "intcode"
version = "0.1.0"
authors = ["Benedikt Werner <1benediktwerner@gmail.com>"]
edition = "2018"

[dependencies]
clap = "2.33"
intcode-vm = { path = "../vm" }
intcode-asm = { path = "../asm" }
intcode-compiler = { path = "../compiler" }
